- name: Add Roboshop Application User
  ansible.builtin.user:
    name: roboshop
  register: appuser

- name: Clean Old App Content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent
## Commented this to move towards standard process of downloading the content from artifact manager rather then downloaing from git repo
#- name: Downloading Appilication Content
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
#    dest: /tmp/
#    remote_src: yes


- name: Create Appilication Directory
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: directory
    owner: roboshop
    group: roboshop


- name: Downloading Appilication Content
  ansible.builtin.unarchive:
    src: http://{{NEXUS_USER}}:{{NEXUS_PASS}}@nexus.vykunta.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop



#- name: Copy Extracted Content
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/
#    dest: /home/roboshop/{{COMPONENT}}/
#    remote_src: yes
#  become_user: roboshop