



- name: NodeJS Setup
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Setup NodeJS repos
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import APP_PreReq Task File
  ansible.builtin.import_tasks: app_prereq.yml

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Import SystemD tasks
  ansible.builtin.import_tasks: systemd.yml